In [16]:
%matplotlib inline
from __future__ import division, print_function
import qutip as qt
import unittest
import numpy as np
from numpy import dot, diag, split, empty_like, zeros, allclose, identity, array
from numpy.random import randn
from numpy.linalg import svd, qr, norm
from functools import reduce
from itertools import product
from qutip import sigmam as sm
import matplotlib.pyplot as plt
import seaborn as sns
import qutip as qo
from qutip import tensor
sns.set()

In [9]:
qt.tensor()

TypeError: Requires at least one input argument

In [17]:
def S_n_body(op, i, n, tensorise=True):
    '''n_body versions of local operators replace tensor with np.array for array of objects'''
    if not i<n:
        raise Exception("i must be less than n")
    l = [op**n for n in map(lambda j: int(not i-j), range(n))]
    if tensorise:
        return tensor(l)
    else:
        return np.array([d.full() for d in l])

In [18]:
def Sp(i, n, tensorise=True):
    return S_n_body(qo.sigmap(), i, n, tensorise)
def Sm(i, n, tensorise=True):
    return S_n_body(qo.sigmam(), i, n, tensorise)
def Sx(i, n, tensorise=True):
    return S_n_body(qo.sigmax(), i, n, tensorise)
def Sy(i, n, tensorise=True):
    return S_n_body(qo.sigmay(), i, n, tensorise)
def Sz(i, n, tensorise=True):
    return S_n_body(qo.sigmaz(), i, n, tensorise)

In [19]:
def spin_half_heisenberg(J, Jz, h, N, tensorise=True):
    NN = sum([J/2*(Sp(i, N, tensorise)*Sm(i+1, N, tensorise)+Sm(i, N, tensorise)*Sp(i+1, N, tensorise))+Jz*Sz(i, N, tensorise)*Sz(i+1, N, tensorise) 
              for i in range(N-1)])
    S = -sum([h*Sz(i, N) for i in range(N)])
    return NN + S

In [21]:
spin_half_heisenberg(1, 1, 1, 10).ground_state()

AttributeError: 'Qobj' object has no attribute 'ground_state'

In [281]:
class block(object):
    def __init__(self, one_site_dim=2):
        self.one_site_dim = one_site_dim
        self.basis = self.canonical_basis(1)
        self.size = 1
        
    def canonical_basis(self, n_sites):
        if n_sites == 0:
            raise Exception("Require at least one site")
        one_site_basis = [qs.basis(self.one_site_dim, k) for k in range(self.one_site_dim)]
        return [tensor(*choice) for choice in product(*([one_site_basis]*n_sites))]
    
    def update(self):
        self.size += 1

def dmrg(time):
    blockA = block()
    blockB = block()
    for t in time:
        blockA.update()
        blockB.update()
    return blockA, blockB

In [246]:
a = np.random.rand(*[3]*3)

In [253]:
a = a/norm(a)
mps = left_canonical_mps(a)
mps.mps

[[array([[-0.48013357,  0.57910044, -0.65887361]]),
  array([[-0.5006447 , -0.79767217, -0.33626476]]),
  array([[-0.72029621,  0.16840958,  0.67291276]])],
 [array([[-0.57725053,  0.22112269, -0.40333856],
         [ 0.10106038,  0.16666868,  0.21674944],
         [ 0.0159662 , -0.65059538, -0.18141742]]),
  array([[-0.59922684,  0.19039448,  0.53557794],
         [ 0.0676347 , -0.10120747,  0.08951652],
         [-0.01426518, -0.30218078, -0.04946054]]),
  array([[-0.49160836, -0.56262721,  0.16077116],
         [-0.22336828,  0.18736942, -0.59509045],
         [-0.02984585, -0.10290312, -0.28309384]])],
 [array([[ 0.37823169],
         [ 0.25949556],
         [-0.03359565]]), array([[ 0.64732916],
         [-0.02653279],
         [ 0.09063338]]), array([[ 0.57845662],
         [-0.13998284],
         [-0.07945745]])]]

In [251]:
sum(map(lambda (x, y): dot(x.T, y), zip(*[mps.mps[0]]*2)))

array([[  1.00000000e+00,   2.49800181e-16,  -2.77555756e-16],
       [  2.49800181e-16,   1.00000000e+00,   2.22044605e-16],
       [ -2.77555756e-16,   2.22044605e-16,   1.00000000e+00]])

In [5]:
tensor()

NameError: name 'tensor' is not defined

In [191]:
mps.mps

[[array([[-0.46318876,  0.03094837, -0.88571913]]),
  array([[-0.73682005, -0.56881017,  0.36544657]]),
  array([[-0.49249607,  0.82188636,  0.28626986]])],
 [array([[-0.44714208],
         [-0.76444324],
         [-0.36264286]]), array([[-0.24103104],
         [ 0.08513212],
         [ 0.1177369 ]]), array([[ 0.01548589],
         [-0.03667897],
         [ 0.05822422]])]]

In [5]:
print(list(reversed(range(1, 5+1))))

[5, 4, 3, 2, 1]


In [7]:
list(range(5))

[0, 1, 2, 3, 4]

In [9]:
list(reversed(range(5+1, 10+1)))

[10, 9, 8, 7, 6]

In [10]:
2**7

128

In [11]:
8*16

128

In [16]:
8//1

8

In [18]:
5//2

2